# =======================================
#  BeginnerManagement
# =======================================
#
# Troll prevention plugin by new players.
# 新規プレイヤーによる荒らし行為防止プラグイン
#
# @author     rypengu23
# @copyright  Copyright ryoengu23 2021-2022
version: 2.0
language: "en"
# =======================================

# DB接続先情報
# Database connection information
# MySQL Only
database:
  hostname: "localhost:3306"
  db: "test"
  user: "user"
  password: "password"

# Discord Related Settings
# To use Discord notifications, you need to enter Discord SRV.
# Discord関連設定
# Discord通知を利用するにはDiscordSRVの道入が必須です。
discord:

  # Whether to notify the Discord SRV console channel if any player is doing something dangerous.
  # 危険行為を行っているプレイヤーが居た場合、DiscordSRVの指定チャンネルに通知するかどうか
  useDiscordSRV: false
  notifyChannelId: ""
  # Whether to notify if the player commits a dangerous act.
  # If you want to notify the mention, enter the Discord user or role ID in notifyMentionId.
  # プレイヤーが危険行為を行った場合、通知するかどうか
  # メンション通知を行いたい場合はnotifyMentionIdにDiscordのユーザーまたはロールのIDを記載
  useDiscordNotify: false
  notifyMentionId: ""

  # Whether to notify if the player is automatically banned.
  # If you want to notify the mention, enter the Discord user or role ID in "notifyMentionId".
  # プレイヤーが自動BANされた場合、通知するかどうか
  # メンション通知を行いたい場合はnotifyMentionIdにDiscordのユーザーまたはロールのIDを記載
  useDiscordNotifyForAutoBan: false
  notifyMentionIdForAutoBan: ""

time:
  # Time from initial login to release of dangerous acts.
  # 初回ログインから危険行為開放までの時間
  day: 0
  hour: 3
  minute: 0

limit:
  # Restrictions on opening dangerous acts.
  # 危険行為開放までの制限事項

  # Items that cannot be obtained from chests, etc.
  # If you specify more than one, separate them with commas. (,)
  # チェスト等から取得不可能なアイテム
  # 複数指定する場合、カンマ区切りで記載 (,)
  items: "TNT,TNT_MINECART,LAVA_BUCKET"

  # Items that cannot be crafted.
  # If you specify more than one, separate them with commas. (,)
  # クラフト不可にするアイテム
  # 複数指定する場合、カンマ区切りで記載 (,)
  craft: "TNT,TNT_MINECART"

  # Blocks that cannot be installed or destroyed.
  # If you specify more than one, separate them with commas. (,)
  # 設置・破壊不可にするブロック
  # 複数指定する場合、カンマ区切りで記載 (,)
  build: "TNT"

  # Disable attackable entity. example) HORSE,CAT etc...
  # If you specify more than one, separate them with commas. (,)
  # 攻撃不可にするエンティティ
  # 複数指定する場合、カンマ区切りで記載 (,)
  damageEntity: "HORSE,CAT"

  # Disable entity. example) MINECART,TNT_MINECART etc...
  # If you specify more than one, separate them with commas. (,)
  # 設置不可にするエンティティ
  # 複数指定する場合、カンマ区切りで記載 (,)
  createEntity: "TNT_MINECART"

  # Use of lava bucket.
  # true:Restrict false:Unrestricted
  # マグマバケツの使用
  # true:制限 false:使用可
  useLavaBucket: false

  # Use of water bucket.
  # true:Restrict false:Unrestricted
  # 水バケツの使用
  # true:制限 false:使用可
  useWaterBucket: false

  # Use of flint and fire charge.
  # true:Restrict false:Unrestricted
  # 火打石・ファイヤーチャージの使用
  # true:制限 false:使用可
  useFlint: false

# How many minutes to limit block destruction from the first login.
# 初回ログインから何分間ブロックの破壊を制限するか
break:
  day: 0
  hour : 0
  minute : 3

# Automatic punishment function.
# 自動処罰機能
autoBan:

  # How many times to punish the restrictions within 10 minutes.
  # 制限事項を10分以内に何回行ったら処罰するか
  numberOfTimes: 10
  # Message at the time of punishment.
  # 処罰時のメッセージ
  reason: ""
  # Whether to do IPBAN at the time of punishment
  # 処罰時にIPBANも行うか
  useIpBan: true

  # Punishment content for each number of punishments
  # KICK：Kick the player from the server.
  # TBAN:(minutes)：BAN the player for the specified time.
  # BAN：BAN the player from the server.
  # When specifying a number, list them separated by commas.
  # If you are punished more than the stated number of punishments, you will be punished with the last one.
  # 処罰回数毎の処罰内容
  # KICK:プレイヤーをサーバーからkickします。
  # TBAN:(minutes):プレイヤーを指定時間BANします。
  # BAN:プレイヤーをサーバーからBANします。
  # 複数指定する場合、カンマ区切りで記載 (1回目の処罰内容,2回目の処罰内容,...)
  # 記載された処罰内容数以上に処罰された場合、最後の内容で処罰を行います。
  detail: "KICK,TBAN:5,TBAN:30,TBAN:60,BAN"

